name: Check

on: push

env: 
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - run: rustup toolchain install stable --profile minimal --no-self-update

    - run: cargo run
